pandoc -f latex -t markdown appdx-contribution-templates.ltx > appdx-contribution-templates.md
pandoc -f latex -t markdown appdx-openness-work.ltx > appdx-openness-work.md
pandoc -f latex -t markdown appdx-open-source-licensing-basics.ltx > appdx-open-source-licensing-basics.md
pandoc -f latex -t markdown appdx-worksheet-ecosystem-map.ltx > appdx-worksheet-ecosystem-map.md
pandoc -f latex -t markdown appdx-worksheet-goals.ltx > appdx-worksheet-goals.md
pandoc -f latex -t markdown arch-b2b.ltx > arch-b2b.md
pandoc -f latex -t markdown arch-bathwater.ltx > arch-bathwater.md
pandoc -f latex -t markdown arch-controlled-ecosystem.ltx > arch-controlled-ecosystem.md
pandoc -f latex -t markdown arch-houseplant.ltx > arch-houseplant.md
pandoc -f latex -t markdown arch-intro.ltx > arch-intro.md
pandoc -f latex -t markdown arch-mass-market.ltx > arch-mass-market.md
pandoc -f latex -t markdown arch-multi-vendor-infra.ltx > arch-multi-vendor-infra.md
pandoc -f latex -t markdown arch-quickref-chart.ltx > arch-quickref-chart.md
pandoc -f latex -t markdown arch-rocket-ship-to-mars.ltx > arch-rocket-ship-to-mars.md
pandoc -f latex -t markdown arch-specialty-library.ltx > arch-specialty-library.md
pandoc -f latex -t markdown arch-trusted-vendor.ltx > arch-trusted-vendor.md
pandoc -f latex -t markdown arch-upstream-dependency.ltx > arch-upstream-dependency.md
pandoc -f latex -t markdown arch-wide-open.ltx > arch-wide-open.md
pandoc -f latex -t markdown benefits-of-open-source.ltx > benefits-of-open-source.md
pandoc -f latex -t markdown business-models.ltx > business-models.md
pandoc -f latex -t markdown choosing-archetype-checklist.ltx > choosing-archetype-checklist.md
pandoc -f latex -t markdown closing.ltx > closing.md
pandoc -f latex -t markdown contributor-expectations.ltx > contributor-expectations.md
pandoc -f latex -t markdown copyright.ltx > copyright.md
pandoc -f latex -t markdown how-to-use.ltx > how-to-use.md
pandoc -f latex -t markdown introduction.ltx > introduction.md
pandoc -f latex -t markdown metrics.ltx > metrics.md
pandoc -f latex -t markdown open-source-archetypes.ltx > open-source-archetypes.md
pandoc -f latex -t markdown preface.ltx > preface.md
pandoc -f latex -t markdown transitions.ltx > transitions.md
pandoc -f latex -t markdown v1-v2.ltx > v1-v2.md
pandoc -f latex -t markdown worksheets.ltx > worksheets.md
